# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='events',
            field=models.ManyToManyField(blank=True, to='upd_calendar.Event', verbose_name='event'),
        ),
    ]
