# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0002_auto_20160326_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='release_date',
            field=models.DateField(blank=True, verbose_name='date released'),
        ),
    ]
