# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0004_auto_20160411_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_deply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test_deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of deployment')),
                ('run', models.CharField(choices=[('y', 'yes'), ('n', 'now')], max_length=1)),
                ('in_time', models.CharField(choices=[('pa', 'past'), ('pr', 'previous'), ('cr', 'current'), ('nx', 'next')], default='ft', max_length=2)),
                ('duration', models.DurationField(verbose_name=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='update',
            name='events',
        ),
        migrations.AddField(
            model_name='update',
            name='test_deploy',
            field=models.ManyToManyField(blank=True, to='upd_calendar.Event', verbose_name='test deploy'),
        ),
        migrations.AlterField(
            model_name='update',
            name='classification',
            field=models.CharField(choices=[('s', 'security'), ('c', 'critical'), ('o', 'other'), ('n', 'not defined')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='update',
            name='product',
            field=models.CharField(choices=[('w7', 'windows 7'), ('w10', 'windows 10'), ('o10', 'office 10'), ('o13', 'office 13')], max_length=4),
        ),
        migrations.AlterField(
            model_name='update',
            name='release_date',
            field=models.DateField(blank=True, verbose_name='date of release'),
        ),
    ]
