# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0005_auto_20160416_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod_deply',
        ),
        migrations.DeleteModel(
            name='Test_deploy',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='date of deployment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='run',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'not')], default='n', max_length=1),
        ),
    ]
