# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0003_auto_20160327_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_time',
            field=models.CharField(choices=[('pa', 'past'), ('pr', 'previous'), ('cr', 'current'), ('nx', 'next'), ('ft', 'future')], default='ft', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='area',
            field=models.CharField(choices=[('t', 'testing'), ('p', 'production')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='run',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'now')], max_length=1),
        ),
    ]
