# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0007_auto_20160507_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='in_time',
        ),
    ]
