# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd_calendar', '0008_remove_event_in_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='complteions date')),
                ('state', models.CharField(default='success', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='update',
            name='test_deploy',
        ),
        migrations.AddField(
            model_name='update',
            name='belongs_rule',
            field=models.ManyToManyField(blank=True, to='upd_calendar.Rule', verbose_name='belongs to rule'),
        ),
    ]
